### ISSUE TITLE
Does Library Support FirebaseFirestore? 

### ISSUE THREAD

**Issue by RowlandOti** [FrangSierra/RxFirebase#53]
Does the library contains the support for Firestone? Is there any documentation on how I can use it?

**Comment by guilhermekrz** [comment]
same here, apparently it does: https://github.com/FrangSierra/RxFirebase/blob/master/app/src/main/java/durdinapps/rxfirebase2/RxFirestore.java

**Comment by f0restgump92** [comment]
I can confirm it does. Simple example would be:
`public Flowable<User> observerUser() {
        return RxFirestore.observeDocumentRef(
                firebaseFirestore.collection("users").document(getUser().getUid()))
                .map(new Function<DocumentSnapshot, User>() {
                    @Override
                    public User apply(DocumentSnapshot documentSnapshot) throws Exception {
                        Timber.d(documentSnapshot.toString());
                        User user = documentSnapshot.toObject(User.class);
                        return user == null ? new User() : user;
                    }
                });
    }`

**Comment by RowlandOti** [comment]
Thank you all for the responses. I love this library. It makes things so much neater.
