### ISSUE TITLE
Specify Id of document in RXFirestore

### ISSUE THREAD

**Issue by RowlandOti** [FrangSierra/RxFirebase#55]
Is it possible to specify the id of the documents we create via `RXFirestore.addDocument()`? I find this very useful feature missing. Could someone help show how to do it?

**Comment by FrangSierra** [comment]
AddDocument recieve a Document or CollectionReference. You just need to create the ID before and add it to your new reference before call `AddDocument`
```
val newFollowedUserId = firestore.collection(PUBLIC_PROFILE).document(uid).collection(FOLLOWING).document()

RxFirestore.addDocument(firestore.collection(PUBLIC_PROFILE).document(uid).collection(FOLLOWING).document(newFollowedUserId)).subscribe()
```

**Comment by juliender** [comment]
Hi, 

thanks for this awesome library.
I can't find the method you talk about.
I watched here https://github.com/FrangSierra/RxFirebase/blob/master/app/src/main/java/durdinapps/rxfirebase2/RxFirestore.java#L125

**Comment by juliender** [comment]
Hi, 

thanks for this awesome library.

I was looking for the method taking "document" argument.
I looked here : https://github.com/FrangSierra/RxFirebase/blob/master/app/src/main/java/durdinapps/rxfirebase2/RxFirestore.java#L125
And I can't find anything.

Do I look at the wrong place ?
Where can I find it ?

Regards

**Comment by FrangSierra** [comment]
Hi @juliender, 

You should use `getDocument()`

```
 /**
     * Reads the document referenced by this DocumentReference.
     *
     * @param ref The given Document reference.
     */
    @NonNull
    public static Maybe<DocumentSnapshot> getDocument(@NonNull final DocumentReference ref) {
        return Maybe.create(new MaybeOnSubscribe<DocumentSnapshot>() {
            @Override
            public void subscribe(final MaybeEmitter<DocumentSnapshot> emitter) throws Exception {
                ref.get().addOnSuccessListener(new OnSuccessListener<DocumentSnapshot>() {
                    @Override
                    public void onSuccess(DocumentSnapshot documentSnapshot) {
                        if (documentSnapshot.exists()) {
                            emitter.onSuccess(documentSnapshot);
                        } else {
                            emitter.onComplete();
                        }
                    }
                }).addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        if (!emitter.isDisposed())
                            emitter.onError(e);
                    }
                });
            }
        });
    }
```

**Comment by juliender** [comment]
Thanks for your quick answer. But I did not get how to use getDocument to create a document.

My current code is simple. If you mind, I will explain what I need.

I signin anonymously and get an FirebaseUser ID `uid`
I query my `users` database with this ID.
Then,  thanks to `switchIfEmpty` method, if it does not exists, I would like to create it with this `uid` as document name.
From now, I add the document with `addDocument` which does not enable to choose document name.
Is there any way to create document  with specific name, with your library ?

    public static Maybe<User> getUser() {
        FirebaseFirestore db = FirebaseFirestore.getInstance();

        return RxFirebaseAuth.signInAnonymously(FirebaseAuth.getInstance())
                .flatMap(authResult -> {

                    String uid = authResult.getUser().getUid();
                    User user = new User(uid);
                    
                    return RxFirestore.getDocument(db.collection("users").document(uid), User.class)
                            .switchIfEmpty(
                                    RxFirestore.addDocument(db.collection("users"), user)
                                            .map(documentReference -> {
                                                user.uid = documentReference.getId();
                                                return user;
                                            }).toMaybe()
                            );

                });
    }

My method `getUser` can be used in any activity, and always returns an User object on my own (defined in my models) and that exists in database.
It's nearly perfect, I just miss how to set my own document name.
But if not possible, I will do differently.

I could also make a pull request if something missing

Regards

**Comment by FrangSierra** [comment]
If you want to create a document with an not-existing ID you need to build the new `documentReference` by yourself and use `addDocument` with it:

Create a new ID from 0:
`String myNewId = db.collection("users").document().getId()` 
`RxFirestore.addDocument(db.collection("users").document(myNewId), user)`

Or you can directly:
`RxFirestore.addDocument(db.collection("users").document(), user)`

The library is a wrapper over Firebase itself, it can do everything that Firebase does. I just added a wrapper of RxJava over the methods. About this specific case, you can find more information about how to work with your data on the official documentation : https://firebase.google.com/docs/firestore/manage-data/add-data

Have a nice day! I hope to have fixed your question

**Comment by juliender** [comment]
Thanks ! But not.  But I found !
After hours of struggling.
I forked the repo and found in javadoc `setDocument` that 

> if the document does not yet exist, it will be created.

Wonderful.
Here is the result.

   
    public static Maybe<User> getUser(){
        FirebaseFirestore db = FirebaseFirestore.getInstance();
        return RxFirebaseAuth.signInAnonymously(FirebaseAuth.getInstance())
                .flatMap(authResult -> {

                    DocumentReference userRef = db.collection("users").document(authResult.getUser().getUid());
                    User user = new User(authResult.getUser().getUid());

                    return RxFirestore.getDocument(userRef, User.class)    // get user
                            .switchIfEmpty(RxFirestore.setDocument(userRef, user).toMaybe());   // update user if does not exist
                });
    }

I can now create users documents named with the authentication user ID, so no need to use queries, everything is very simple.

Thanks again for your help
