### ISSUE TITLE
Latest build not available on jitpack

### ISSUE THREAD

**Issue by jbenezech** [FrangSierra/RxFirebase#57]
https://jitpack.io/com/github/frangsierra/rx2firebase/1.5.0/build.log

**Comment by gracefulife** [comment]
+1

**Comment by FrangSierra** [comment]
I'm on it.

For some reason if I update the `google:support` library for the recyclerView it crash for some dependencies.

A new version will be released as soon as I will fix it.

**Comment by AndrewReitz** [comment]
I think it is available, just the path is wrong in the readme. I found it here https://jitpack.io/#FrangSierra/RxFirebase/1.5.0

**Comment by kylerob** [comment]
@FrangSierra I was able to update the `google:support` lib and get rid of the corresponding lint issues by adding the following explicit dependencies (see https://stackoverflow.com/questions/42374151/all-com-android-support-libraries-must-use-the-exact-same-version-specification): 
```
provided "com.android.support:support-fragment:$support_version"
provided "com.android.support:support-media-compat:$support_version"
provided "com.android.support:support-v4:$support_version"
```
I couldn't figure out a way to fix the remaining `com.google.android.gms:play-services-measurement-base:15.0.2` issue though, so I ended up adding `abortOnError false` to build it locally and include it in my project manually. Hopefully that helps get everything a step closer. I'll update if I find a way to get the version difference between `play-services-measurement-base` and `play-services-ads-identifier` worked out.

**Comment by FrangSierra** [comment]
My fault. As @AndrewReitz  said. After change the name to the repository the Jitpack generated version has a different name. You can find it already updated on the Readme or just clicking on https://jitpack.io/#FrangSierra/RxFirebase/1.5.0

Thank you so much for the support! Will upload a need version soon with the methods for ML Kit and fixing other minor issues.
