### ISSUE TITLE
using rxfirebase in android things/enum/kotlin project

### ISSUE THREAD

**Issue by neuberfran** [FrangSierra/RxFirebase#67]
https://stackoverflow.com/questions/52639350/kotlin-enum-class-with-companion-object-integrate-with-field-of-the-firebase-dat

Hi,

I need your help to integrate rxfirebase in my project

can I use kotlin with your library? or not

**Comment by FrangSierra** [comment]
Yes, you can use the library on Kotlin without no problem. 
The kotlin has interoperability with java.

**Comment by neuberfran** [comment]
https://stackoverflow.com/questions/52639350/kotlin-enum-class-with-companion-object-integrate-with-field-of-the-firebase-dat

How to your library can help me in this
