### ISSUE TITLE
Cannot get Firestore collection observable

### ISSUE THREAD

**Issue by szaske** [FrangSierra/RxFirebase#68]
I'm trying to get your library to work.  I want to track a collection of objects.  I can get my list of objects using the following code:

```
override fun getPois(): Observable<List<PoiRepository>> {

        return Observable.create { emitter: ObservableEmitter<List<PoiRepository>> ->

            val observableProducer = database.collection(KEY_POIS)
                    .addSnapshotListener(EventListener<QuerySnapshot> { querySnapshot, e ->

                        // Check to see if an error occurred.
                        if (e != null) {
                            emitter.onError(e)
                            return@EventListener
                        }
                        if (!querySnapshot!!.isEmpty) {
                            val results = mutableListOf<PoiRepository>()
                            for (document in querySnapshot.documents) {
                                val sentPOI = document.toObject(FireStorePoiResponse::class.java)
                                results.add(sentPOI!!.mapToRepository())
                            }

                            emitter.onNext(results)
                        } else {
                            Log.d(TAG, " QuerySnapshot is empty")
                        }
                    })
            emitter.setCancellable { observableProducer.remove() }
        }
    }
```

But for the life of me I cannot get your library to work.  Can someone share an example of using the library to fetch a collection of objects from Firestore?

**Comment by FrangSierra** [comment]
You should use `getCollection` for single calls, and `observeQueryRef` if you wanna keep listening changes of that query until `dispose` is called.
All this information is exposed in the javadoc of the API.

**Comment by o-nos** [comment]
Ok, that's nice to have `observeQueryRef`, but it does not emit an empty list in the case when a collection does not contain any data. And this causes a problem when I `combineLatest`, where one of the Flowables is your `observeQueryRef` where collection is empty.

Could you please emit empty list in this case?
