### ISSUE TITLE
RxFirebaseRecyclerAdapter is no longer available

### ISSUE THREAD

**Issue by SilentThunder89** [FrangSierra/RxFirebase#79]
I noticed that `RxFirebaseRecyclerAdapter` is no longer in the library, is there a reason for its removal? is there a replacement?

also, the readme still mentions it so it might be a bit confusing for new users.

**Comment by FrangSierra** [comment]
Is no longer available because https://github.com/firebase/FirebaseUI-Android provides a better implementation and have a bigger community to support it. It was just an UI helper, so in the end it doesn't fit that much in the library.

I have updated the README, thx 😄
