### ISSUE TITLE
Cannot reslove method 'subscribe'

### ISSUE THREAD

**Issue by SoulSlayerAbad** [FrangSierra/RxFirebase#80]
Hi all. When trying to run the simple observeSingleValueEvent method from the documentation, AndroidStudio gives me the following error. 
![Issue](https://user-images.githubusercontent.com/30027453/57574728-6f4bfc80-744f-11e9-9020-d873625691a8.PNG)

Could anybody lead me as to where or what I am doing wrong?

**Comment by FrangSierra** [comment]
It looks that you are importing RxFirebase to your gradle project, but you are not adding RxJava aswell. For that reason `subscribe` method is not in your project.

```
implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
implementation 'io.reactivex.rxjava2:rxjava:2.0.8'
```
